let tabledata = [
  {
    id: 1,
    Id: 1,
    username: "admin",
    email: "admin@somemail.com",
    ip: "::1",
    time: "27-Nov-20 08:30",
    login: "27-Nov-20 09:00",
    confirmation: "Confirmed",
    status: "Block",
  },
  {
    id: 2,
    Id: 2,
    username: "officer",
    user_id: 2,
    email: "officer1@somemail.com",
    ip: "::1",
    time: "27-Nov-20 08:30",
    login: "27-Nov-20 09:00",
    confirmation: "Confirmed",
    status: "Block",
  },
  {
    id: 3,
    Id: 1,
    email_id: 3,
    username: "admin",
    email: "admin@somemail.com",
    ip: "::1",
    time: "27-Nov-20 08:30",
    login: "27-Nov-20 09:00",
    confirmation: "Confirmed",
    status: "Block",
  },
  {
    id: 4,
    Id: 2,
    username: "officer",
    email: "officer1@somemail.com",
    ip: "::1",
    time: "27-Nov-20 08:30",
    login: "27-Nov-20 09:00",
    confirmation: "Confirmed",
    status: "Block",
  },
  {
    id: 5,
    Id: 1,
    username: "admin",
    email: "admin@somemail.com",
    ip: "::1",
    time: "27-Nov-20 08:30",
    login: "27-Nov-20 09:00",
    confirmation: "Confirmed",
    status: "Block",
  },
  {
    id: 6,
    Id: 2,
    username: "officer",
    email: "admin@somemail.com",
    ip: "::1",
    time: "27-Nov-20 08:30",
    login: "27-Nov-20 09:00",
    confirmation: "Confirmed",
    status: "Block",
  },
];

export { tabledata };
